sudo: required
dist: xenial
language: cpp

addons:
  apt:
    sources:
      github-git-lfs-bionic
    packages:
      git-lfs
      
cache:
  - apt
  - directories:
    - Tools

compiler:
  - g++

os:
  - unix

jdk:
  #- oraclejdk8
  #- oraclejdk9
  - openjdk8

#android:
#  components:
#    - build-tools-28.0.3
#    - android-24
    
addons:
  ssh_known_hosts:
    - github.com
    - frs.sourceforge.net

env:
  global:
    - SOURCE_DIR=$TRAVIS_BUILD_DIR
    - PROJECT_NAME="RabbitThirdLIbrary"
    - BUILD_VERSION=$TRAVIS_BUILD_NUMBER
    - RABBIT_USE_REPOSITORIES="TRUE"
    - QMAKE=qmake
    - RABBIT_BUILD_THIRDLIBRARY="TRUE" 
    
  matrix:
    - BUILD_TARGERT="unix" QT_VERSION_DIR=512 QT_VERSION=5.12.3 RABBIT_NUMBER=0 DOWNLOAD_QT=FALSE
    - BUILD_TARGERT="unix" QT_VERSION_DIR=512 QT_VERSION=5.12.3 RABBIT_NUMBER=1 DOWNLOAD_QT=FALSE
    - BUILD_TARGERT="unix" QT_VERSION_DIR=512 QT_VERSION=5.12.3 RABBIT_NUMBER=2 DOWNLOAD_QT=FALSE
    - BUILD_TARGERT="unix" QT_VERSION_DIR=512 QT_VERSION=5.12.3 RABBIT_NUMBER=3 DOWNLOAD_QT=FALSE
    - BUILD_TARGERT="unix" QT_VERSION_DIR=512 QT_VERSION=5.12.3 RABBIT_NUMBER=4 DOWNLOAD_QT=FALSE
    
    #- BUILD_TARGERT="unix" QT_VERSION_DIR=511 QT_VERSION=5.11.3 DOWNLOAD_QT=FALSE STATIC=ON

    #- BUILD_TARGERT="unix" BUILD_ARCH="unix" QT_VERSION_DIR=5.12 QT_VERSION=5.12.5 DOWNLOAD_QT=TRUE

    - BUILD_TARGERT="android" RABBIT_ARCH="armeabi-v7a" QT_VERSION_DIR=5.12 QT_VERSION=5.12.5 ANDROID_API=android-24 DOWNLOAD_QT=TRUE RABBIT_NUMBER=0
    - BUILD_TARGERT="android" RABBIT_ARCH="armeabi-v7a" QT_VERSION_DIR=5.12 QT_VERSION=5.12.5 ANDROID_API=android-24 DOWNLOAD_QT=TRUE RABBIT_NUMBER=1
    - BUILD_TARGERT="android" RABBIT_ARCH="armeabi-v7a" QT_VERSION_DIR=5.12 QT_VERSION=5.12.5 ANDROID_API=android-24 DOWNLOAD_QT=TRUE RABBIT_NUMBER=2
    - BUILD_TARGERT="android" RABBIT_ARCH="armeabi-v7a" QT_VERSION_DIR=5.12 QT_VERSION=5.12.5 ANDROID_API=android-24 DOWNLOAD_QT=TRUE RABBIT_NUMBER=3
    - BUILD_TARGERT="android" RABBIT_ARCH="armeabi-v7a" QT_VERSION_DIR=5.12 QT_VERSION=5.12.5 ANDROID_API=android-24 DOWNLOAD_QT=TRUE RABBIT_NUMBER=4
    
    #- BUILD_TARGERT="android" RABBIT_ARCH="armeabi-v7a" QT_VERSION_DIR=5.13 QT_VERSION=5.13.2 ANDROID_API=android-24 DOWNLOAD_QT=TRUE STATIC=ON
    #- BUILD_TARGERT="android" RABBIT_ARCH="x86" QT_VERSION_DIR=5.12 QT_VERSION=5.12.5 ANDROID_API=android-24 DOWNLOAD_QT=TRUE

before_install:
  - echo "TRAVIS_OS_NAME=${TRAVIS_OS_NAME}"
  - echo "JAVA_HOME=${JAVA_HOME}"
  - sudo apt-get install -y -qq xvfb xpra
  - sudo Xvfb :99 -ac &
  - export DISPLAY=:99.0
  - mkdir ${SOURCE_DIR}/Tools
  - export VERSION="v0.0.2"
  
install:
  - bash build_script/ci/build-install-apt.sh > /dev/null
  - bash build_script/ci/build-install-tools.sh > /dev/null

before_script:
  - source ${TRAVIS_BUILD_DIR}/build_script/ci/build_env.sh
  - cd ${TRAVIS_BUILD_DIR}/build_script

script: 
  - bash ${TRAVIS_BUILD_DIR}/build_script/ci/build.sh ${TRAVIS_BUILD_DIR} #> /dev/null
  #- bash ${TRAVIS_BUILD_DIR}/build_script/ci/Deploy.sh ${TRAVIS_BUILD_DIR}

after_script:

notifications:
  email: kl222@126.com
  on_success: never  # [always|never|change]
  on_failure: always

deploy:
  provider: releases
  api_key: 177ce637a8ec54e66ea8693092caf35059cf95d7
  file: 
    - ./build_android/android-build/bin/QtApp-debug.apk
  skip_cleanup: true
  on:
    condition: $TRAVIS_OS_NAME = android
    repo: KangLin/RabbitThirdLibrary
    tags: true
