sudo: required
dist: trusty

language: cpp

cache:
  - apt
  - directories:
    - Tools

compiler:
  - g++

jdk: oraclejdk7

os:
  - unix
  - android
  
#addons:
#  ssh_known_hosts: frs.sourceforge.net
  
env:
  global:
    - PROJECT_NAME="RabbitThirdLIbrary"
    - BUILD_VERSION=$TRAVIS_BUILD_NUMBER
    - RABBIT_USE_REPOSITORIES="TRUE"
    - QMAKE=qmake
    - RABBIT_BUILD_THIRDLIBRARY="TRUE" 
    
  matrix:
    - BUILD_TARGERT="unix" RABBIT_ARCH=amd64
    
    - BUILD_TARGERT="android" BUILD_ARCH="armeabi-v7a" QT_VERSION_DIR=5.12 QT_VERSION=5.12.4 ANDROID_PLATFORM=android-24 BUILD_DOWNLOAD=TRUE
    - BUILD_TARGERT="android" BUILD_ARCH="armeabi-v7a" QT_VERSION_DIR=5.9 QT_VERSION=5.9.7 ANDROID_PLATFORM=android-18 BUILD_DOWNLOAD=TRUE STATIC=ON
    - BUILD_TARGERT="android" BUILD_ARCH="x86" QT_VERSION_DIR=5.9 QT_VERSION=5.9.7 ANDROID_PLATFORM=android-18 BUILD_DOWNLOAD=TRUE

before_install:
  - echo "TRAVIS_OS_NAME=${TRAVIS_OS_NAME}"
  - echo "JAVA_HOME=${JAVA_HOME}"
  - export DISPLAY=:99.0
  - bash -e /etc/init.d/xvfb start

install:
  - bash build_script/ci/build-install-apt.sh > /dev/null
  - bash build_script/ci/build-install-tools.sh > /dev/null

before_script:
  - source ${TRAVIS_BUILD_DIR}/build_script/ci/build_env.sh
  - cd ${TRAVIS_BUILD_DIR}/build_script

script: 
  - bash ${TRAVIS_BUILD_DIR}/build_script/ci/build.sh ${TRAVIS_BUILD_DIR} #> /dev/null
  #- bash ${TRAVIS_BUILD_DIR}/build_script/ci/Deploy.sh ${TRAVIS_BUILD_DIR}

after_script:

notifications:
  email: kl222@126.com
  on_success: never  # [always|never|change]
  on_failure: always

deploy:
  provider: releases
  api_key: 177ce637a8ec54e66ea8693092caf35059cf95d7
  file: 
    - ./build_android/android-build/bin/QtApp-debug.apk
  skip_cleanup: true
  on:
    condition: $TRAVIS_OS_NAME = android
    repo: KangLin/RabbitThirdLibrary
    tags: true
