sudo: required
dist: bionic
#language: cpp

cache:
  directories: build

env:
  global:
    - SOURCE_DIR=$TRAVIS_BUILD_DIR
    - PROJECT_NAME="RabbitThirdLIbrary"
    - BUILD_VERSION=$TRAVIS_BUILD_NUMBER
    #- RABBIT_USE_REPOSITORIES="TRUE"
    - QMAKE=qmake
    - RABBIT_BUILD_THIRDLIBRARY="TRUE"

jobs:
  include:
    ############################# android arm #########################
    - stage: stage1
      language: android
#      android:
#        components:
#          - build-tools-28.0.2
#          - android-24
      env:
        - BUILD_TARGERT="android"
        - BUILD_ARCH="arm"
        - ANDROID_API=android-24
      before_script:
        - export RABBIT_NUMBER=0
        - rm -fr build
        
    - stage: stage2
      language: android
#      android:
#        components:
#          - build-tools-28.0.2
#          - android-24
      env:
        - BUILD_TARGERT="android"
        - BUILD_ARCH="arm"
        - ANDROID_API=android-24
      before_script:
        - export RABBIT_NUMBER=1
        - export DOWNLOAD_QT=TRUE
        - export QT_VERSION_DIR=5.12
        - export QT_VERSION=5.12.8
        
    ############################# android arm64 #########################
    - stage: stage1
      language: android
#      android:
#        components:
#          - build-tools-28.0.2
#          - android-24
      env:
        - BUILD_TARGERT="android"
        - BUILD_ARCH="arm64"
        - ANDROID_API=android-24
      before_script:
        - export RABBIT_NUMBER=0
        - rm -fr build
        
    - stage: stage2
      language: android
#      android:
#        components:
#          - build-tools-28.0.2
#          - android-24
      env:
        - BUILD_TARGERT="android"
        - BUILD_ARCH="arm64"
        - ANDROID_API=android-24
      before_script:
        - export RABBIT_NUMBER=1
        - export DOWNLOAD_QT=TRUE
        - export QT_VERSION_DIR=5.12
        - export QT_VERSION=5.12.8
    
    ############################# android x86 #########################
    - stage: stage1
      language: android
#      android:
#        components:
#          - build-tools-28.0.2
#          - android-24
      env:
        - BUILD_TARGERT="android"
        - BUILD_ARCH="x86"
        - ANDROID_API=android-24
      before_script:
        - export RABBIT_NUMBER=0
        - rm -fr build
    
    - stage: stage2
      language: android
#      android:
#        components:
#          - build-tools-28.0.2
#          - android-24
      env:
        - BUILD_TARGERT="android"
        - BUILD_ARCH="x86"
        - ANDROID_API=android-24
      before_script:
        - export RABBIT_NUMBER=1
        - export DOWNLOAD_QT=TRUE
        - export QT_VERSION_DIR=5.12
        - export QT_VERSION=5.12.8
        
    ############################# android x86_64 #########################
    - stage: stage1
      language: android
#      android:
#        components:
#          - build-tools-28.0.2
#          - android-24
      env:
        - BUILD_TARGERT="android"
        - BUILD_ARCH="x86_64"
        - ANDROID_API=android-24
      before_script:
        - export RABBIT_NUMBER=0
        - rm -fr build
    
    - stage: stage2
      language: android
#      android:
#        components:
#          - build-tools-28.0.2
#          - android-24
      env:
        - BUILD_TARGERT="android"
        - BUILD_ARCH="x86_64"
        - ANDROID_API=android-24
      before_script:
        - export RABBIT_NUMBER=1
        - export DOWNLOAD_QT=TRUE
        - export QT_VERSION_DIR=5.12
        - export QT_VERSION=5.12.8
        
    ############################# unix #########################
    - stage: stage1
      language: cpp
      env:
        - BUILD_TARGERT="unix"
        - BUILD_ARCH="x86_64"
      before_script:
        - export RABBIT_NUMBER=0
        - rm -fr build

    - stage: stage2
      language: cpp
      env:
        - BUILD_TARGERT="unix"
        - BUILD_ARCH="x86_64"
      before_script:
        - export RABBIT_NUMBER=1
        - export DOWNLOAD_QT=APT

before_install:
  - echo "TRAVIS_OS_NAME=${TRAVIS_OS_NAME}"
  - echo "JAVA_HOME=${JAVA_HOME}"
  - sudo apt-get install -y -qq xvfb xpra
  - sudo Xvfb :99 -ac &
  - export DISPLAY=:99.0
  - export VERSION="v0.0.2"

install:
  - sudo apt-get update -y -qq

script:
  - ./build_script/ci/build-install-tools.sh ${TRAVIS_BUILD_DIR} #> /dev/null
  - ./build_script/ci/build_linux.sh ${TRAVIS_BUILD_DIR} #> /dev/null

#deploy:
#  provider: releases
#  api_key: 
#    secure: ${GITHUB_TOKEN}
#  file_glob: true
#  file: 
#
#  skip_cleanup: true
#  on:
   #condition: $TRAVIS_OS_NAME = android
   # repo: KangLin/RabbitThirdLibrary
#    tags: true
