sudo: required
dist: trusty

language: cpp

cache:
  - apt
  - directories:
    - Tools

compiler:
  - g++

jdk: oraclejdk7

os:
  - unix

addons:
  ssh_known_hosts: frs.sourceforge.net
  
env:
  global:
    - SOURCE_DIR=$TRAVIS_BUILD_DIR
    - RABBITIM_USE_REPOSITORIES="TRUE"
    - QMAKE=qmake
    - RABBITIM_BUILD_THIRDLIBRARY="TRUE" 

  matrix:
     - BUILD_TARGERT="unix" RABBITIM_BUILD_THIRDLIBRARY="change_prefix zlib minizip expat libgpx openssl libsodium libcurl libpng jpeg libgif libtiff freetype libvpx libyuv libopus x264 ffmpeg opencv"
     - BUILD_TARGERT="android" RABBITIM_BUILD_THIRDLIBRARY="change_prefix zlib minizip expat libgpx openssl libsodium libcurl libpng jpeg libgif libtiff freetype libvpx libyuv libopus x264 ffmpeg opencv"
     
     #- BUILD_TARGERT="unix" QT_VERSION_DIR=5.7 QT_VERSION=5.7.0 RABBITIM_BUILD_THIRDLIBRARY="qxmpp qzxing" DOWNLOAD_FILE: https://sourceforge.net/projects/rabbitim-third-library/files/release/RabbitIm_linux_x86__v$(appveyor_build_version).zip/download
     #- BUILD_TARGERT="unix" QT_VERSION_DIR=5.6 QT_VERSION=5.6.0 RABBITIM_BUILD_THIRDLIBRARY="qxmpp qzxing"
     #- BUILD_TARGERT="unix" QT_VERSION_DIR=5.5 QT_VERSION=5.5.1 RABBITIM_BUILD_THIRDLIBRARY="qxmpp qzxing"
     #- BUILD_TARGERT="unix" QT_VERSION_DIR=5.4 QT_VERSION=5.4.2 RABBITIM_BUILD_THIRDLIBRARY="qxmpp qzxing"
     #- BUILD_TARGERT="unix" QT_VERSION_DIR=5.3 QT_VERSION=5.3.2 RABBITIM_BUILD_THIRDLIBRARY="qxmpp qzxing"
     #- BUILD_TARGERT="unix" QT_VERSION_DIR=5.2 QT_VERSION=5.2.1 RABBITIM_BUILD_THIRDLIBRARY="qxmpp qzxing"

     #- BUILD_TARGERT="android" QT_VERSION_DIR=5.7 QT_VERSION=5.7.0 RABBITIM_BUILD_THIRDLIBRARY="qxmpp qzxing"
     #- BUILD_TARGERT="android" QT_VERSION_DIR=5.6 QT_VERSION=5.6.0 RABBITIM_BUILD_THIRDLIBRARY="qxmpp qzxing"
     #- BUILD_TARGERT="android" QT_VERSION_DIR=5.5 QT_VERSION=5.5.1 RABBITIM_BUILD_THIRDLIBRARY="qxmpp qzxing"

before_install:
  - echo "TRAVIS_OS_NAME=${TRAVIS_OS_NAME}"
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - bash build_script/ci/build-install-apt.sh > /dev/null
  - bash build_script/ci/build-install-tools.sh > /dev/null

before_script:
  - source ${SOURCE_DIR}/build_script/ci/build_env.sh
  - cd ${SOURCE_DIR}/build_script

script: 
  - bash ${SOURCE_DIR}/build_script/ci/build.sh ${SOURCE_DIR}

after_script:

notifications:
  email: kl222@126.com
  on_success: never  # [always|never|change]
  on_failure: always

deploy:
  provider: releases
  api_key: 177ce637a8ec54e66ea8693092caf35059cf95d7
  file: 
    - ./build_android/android-build/bin/QtApp-debug.apk
  skip_cleanup: true
  on:
    condition: $TRAVIS_OS_NAME = android
    repo: KangLin/rabbitim
    tags: true
