#TODO:版本变更时，修改成相应的版本
version: '0.1.1.{build}'

os: Visual Studio 2015

environment:
  matrix:
  ##############  test ######################
  ##############  test ######################

  - BUILD_TARGERT: windows_msvc
    GENERATORS: "Visual Studio 14 2015"
    TOOLCHAIN_VERSION: 14
    QT_VERSION: NO
    AUTOBUILD_ARCH: x86
    RABBIT_BUILD_THIRDLIBRARY: change_prefix zlib minizip expat libgpx openssl libsodium libcurl libpng jpeg libgif libtiff freetype libyuv libvpx libopus x264 ffmpeg #opencv
    RABBIT_USE_REPOSITORIES: "FALSE"
    PASSWORD:
      secure: 2WEtOQrdty3V3g0aEVvS3Q==

  - BUILD_TARGERT: windows_msvc
    GENERATORS: "Visual Studio 12 2013"
    TOOLCHAIN_VERSION: 12
    QT_VERSION: NO
    AUTOBUILD_ARCH: x86
    RABBIT_BUILD_THIRDLIBRARY: change_prefix zlib minizip expat libgpx openssl libsodium libcurl libpng jpeg libgif libtiff freetype libyuv libvpx libopus x264 ffmpeg #opencv 
    PASSWORD:
      secure: 2WEtOQrdty3V3g0aEVvS3Q==

  - BUILD_TARGERT: android
    TOOLCHAIN_VERSION: 4.8
    QT_VERSION: NO
    AUTOBUILD_ARCH: arm
    RABBIT_BUILD_THIRDLIBRARY: change_prefix zlib minizip expat libgpx openssl libsodium libcurl libpng jpeg libgif libtiff freetype libyuv libvpx libopus x264 ffmpeg #opencv 
    RABBIT_USE_REPOSITORIES: "FALSE"
    PASSWORD:
      secure: 2WEtOQrdty3V3g0aEVvS3Q==

  - BUILD_TARGERT: windows_mingw
    TOOLCHAIN_VERSION: 530
    QT_VERSION: NO
    AUTOBUILD_ARCH: x86
    RABBIT_BUILD_THIRDLIBRARY: change_prefix zlib minizip expat libgpx openssl libsodium libcurl libpng jpeg libgif libtiff freetype libyuv libvpx libopus x264 ffmpeg qrencode #opencv 
    PASSWORD:
      secure: 2WEtOQrdty3V3g0aEVvS3Q==

  - BUILD_TARGERT: windows_mingw
    TOOLCHAIN_VERSION: 492
    QT_VERSION: NO
    AUTOBUILD_ARCH: x86
    RABBIT_BUILD_THIRDLIBRARY: change_prefix zlib minizip expat libgpx openssl libsodium libcurl libpng jpeg libgif libtiff freetype libyuv libvpx libopus x264 ffmpeg qrencode #opencv 
    RABBIT_USE_REPOSITORIES: "FALSE"
    PASSWORD:
      secure: 2WEtOQrdty3V3g0aEVvS3Q==

  ##### QT相关编译 #####
  
  ##### osg #####
  - BUILD_TARGERT: windows_msvc
    RABBIT_BUILD_THIRDLIBRARY: osg 
    TOOLCHAIN_VERSION: 14
    QT_VERSION: qt5.7
    QT_ROOT: /C/Qt/5.7/msvc2015
    GENERATORS: "Visual Studio 14 2015"
    AUTOBUILD_ARCH: x86
    DOWNLOAD_FILE: https://sourceforge.net/projects/rabbitthirdlibrary/files/Release/rabbit_windows_msvc14_x86_NO_v$(appveyor_build_version).tar.gz/download
    RABBIT_USE_REPOSITORIES: "FALSE"
    PASSWORD:
      secure: 2WEtOQrdty3V3g0aEVvS3Q==

  - BUILD_TARGERT: windows_msvc
    RABBIT_BUILD_THIRDLIBRARY: osg 
    TOOLCHAIN_VERSION: 14
    QT_VERSION: qt5.6.1
    QT_ROOT: /C/Qt/5.6/msvc2015
    GENERATORS: "Visual Studio 14 2015"
    AUTOBUILD_ARCH: x86
    DOWNLOAD_FILE: https://sourceforge.net/projects/rabbitthirdlibrary/files/Release/rabbit_windows_msvc14_x86_NO_v$(appveyor_build_version).tar.gz/download
    PASSWORD:
      secure: 2WEtOQrdty3V3g0aEVvS3Q==

  - BUILD_TARGERT: windows_msvc
    RABBIT_BUILD_THIRDLIBRARY: osg 
    TOOLCHAIN_VERSION: 12
    QT_VERSION: qt5.7
    QT_ROOT: /C/Qt/5.7/msvc2013
    GENERATORS: "Visual Studio 12 2013"
    AUTOBUILD_ARCH: x86
    DOWNLOAD_FILE: https://sourceforge.net/projects/rabbitthirdlibrary/files/Release/rabbit_windows_msvc12_x86_NO_v$(appveyor_build_version).tar.gz/download
    PASSWORD:
      secure: 2WEtOQrdty3V3g0aEVvS3Q==

  - BUILD_TARGERT: windows_msvc
    RABBIT_BUILD_THIRDLIBRARY: osg
    TOOLCHAIN_VERSION: 12
    QT_VERSION: qt5.6.1
    QT_ROOT: /C/Qt/5.6/msvc2013
    GENERATORS: "Visual Studio 12 2013"
    AUTOBUILD_ARCH: x86
    DOWNLOAD_FILE: https://sourceforge.net/projects/rabbitthirdlibrary/files/Release/rabbit_windows_msvc12_x86_NO_v$(appveyor_build_version).tar.gz/download
    RABBIT_USE_REPOSITORIES: "FALSE"
    PASSWORD:
      secure: 2WEtOQrdty3V3g0aEVvS3Q==

  - BUILD_TARGERT: android
    RABBIT_BUILD_THIRDLIBRARY: osg
    QT_VERSION_DIR: 5.7
    QT_VERSION: 5.7.0
    TOOLCHAIN_VERSION: 4.8
    AUTOBUILD_ARCH: arm
    DOWNLOAD_FILE: https://sourceforge.net/projects/rabbitthirdlibrary/files/Release/rabbit_android4.8_arm_NO_v$(appveyor_build_version).tar.gz/download
    PASSWORD:
      secure: 2WEtOQrdty3V3g0aEVvS3Q==

  - BUILD_TARGERT: android
    RABBIT_BUILD_THIRDLIBRARY: osg
    QT_VERSION_DIR: 5.6
    QT_VERSION: 5.6.1
    TOOLCHAIN_VERSION: 4.8
    AUTOBUILD_ARCH: arm
    DOWNLOAD_FILE: https://sourceforge.net/projects/rabbitthirdlibrary/files/Release/rabbit_android4.8_arm_NO_v$(appveyor_build_version).tar.gz/download
    RABBIT_USE_REPOSITORIES: "FALSE"
    PASSWORD:
      secure: 2WEtOQrdty3V3g0aEVvS3Q==

  - BUILD_TARGERT: windows_mingw
    RABBIT_BUILD_THIRDLIBRARY: osg
    TOOLCHAIN_VERSION: 530
    QT_VERSION: qt5.7
    QT_ROOT: /C/Qt/5.7/mingw53_32
    AUTOBUILD_ARCH: x86
    DOWNLOAD_FILE: https://sourceforge.net/projects/rabbitthirdlibrary/files/Release/rabbit_windows_mingw530_x86_NO_v$(appveyor_build_version).tar.gz/download
    RABBIT_USE_REPOSITORIES: "FALSE"
    PASSWORD:
      secure: 2WEtOQrdty3V3g0aEVvS3Q==

  - BUILD_TARGERT: windows_mingw
    RABBIT_BUILD_THIRDLIBRARY: osg
    TOOLCHAIN_VERSION: 492
    QT_VERSION: qt5.6
    QT_ROOT: /C/Qt/5.6/mingw49_32
    AUTOBUILD_ARCH: x86
    DOWNLOAD_FILE: https://sourceforge.net/projects/rabbitthirdlibrary/files/Release/rabbit_windows_mingw492_x86_NO_v$(appveyor_build_version).tar.gz/download
    #RABBIT_USE_REPOSITORIES: "FALSE"
    PASSWORD:
      secure: 2WEtOQrdty3V3g0aEVvS3Q==
  ##### osg #####
  
  ##### gdal osgearth #####
  - BUILD_TARGERT: windows_msvc
    TOOLCHAIN_VERSION: 14
    QT_VERSION: qt5.7
    RABBIT_BUILD_THIRDLIBRARY: gdal osgearth
    QT_ROOT: /C/Qt/5.7/msvc2015
    GENERATORS: "Visual Studio 14 2015"
    AUTOBUILD_ARCH: x86
    DOWNLOAD_FILE: https://sourceforge.net/projects/rabbitthirdlibrary/files/Release/rabbit_windows_msvc14_x86_qt5.7_v$(appveyor_build_version).tar.gz/download
    PASSWORD:
      secure: 2WEtOQrdty3V3g0aEVvS3Q==

  - BUILD_TARGERT: windows_msvc
    TOOLCHAIN_VERSION: 14
    QT_VERSION: qt5.6.1
    RABBIT_BUILD_THIRDLIBRARY: gdal osgearth
    QT_ROOT: /C/Qt/5.6/msvc2015
    GENERATORS: "Visual Studio 14 2015"
    AUTOBUILD_ARCH: x86
    DOWNLOAD_FILE: https://sourceforge.net/projects/rabbitthirdlibrary/files/Release/rabbit_windows_msvc14_x86_qt5.6.1_v$(appveyor_build_version).tar.gz/download
    RABBIT_USE_REPOSITORIES: "FALSE"
    PASSWORD:
      secure: 2WEtOQrdty3V3g0aEVvS3Q==
      
  - BUILD_TARGERT: windows_msvc
    TOOLCHAIN_VERSION: 12
    QT_VERSION: qt5.7
    RABBIT_BUILD_THIRDLIBRARY: gdal osgearth 
    QT_ROOT: /C/Qt/5.7/msvc2013
    GENERATORS: "Visual Studio 12 2013"
    AUTOBUILD_ARCH: x86
    DOWNLOAD_FILE: https://sourceforge.net/projects/rabbitthirdlibrary/files/Release/rabbit_windows_msvc12_x86_qt5.7_v$(appveyor_build_version).tar.gz/download
    PASSWORD:
      secure: 2WEtOQrdty3V3g0aEVvS3Q==

  - BUILD_TARGERT: windows_msvc
    TOOLCHAIN_VERSION: 12
    QT_VERSION: qt5.6.1
    RABBIT_BUILD_THIRDLIBRARY: gdal osgearth
    QT_ROOT: /C/Qt/5.6/msvc2013
    GENERATORS: "Visual Studio 12 2013"
    AUTOBUILD_ARCH: x86
    DOWNLOAD_FILE: https://sourceforge.net/projects/rabbitthirdlibrary/files/Release/rabbit_windows_msvc12_x86_qt5.6.1_v$(appveyor_build_version).tar.gz/download
    RABBIT_USE_REPOSITORIES: "FALSE"
    PASSWORD:
      secure: 2WEtOQrdty3V3g0aEVvS3Q==

  - BUILD_TARGERT: android
    RABBIT_BUILD_THIRDLIBRARY: gdal osgearth
    QT_VERSION_DIR: 5.7
    QT_VERSION: 5.7.0
    TOOLCHAIN_VERSION: 4.8
    AUTOBUILD_ARCH: arm
    DOWNLOAD_FILE: https://sourceforge.net/projects/rabbitthirdlibrary/files/Release/rabbit_android4.8_arm_5.7.0_v$(appveyor_build_version).tar.gz/download
    PASSWORD:
      secure: 2WEtOQrdty3V3g0aEVvS3Q==

  - BUILD_TARGERT: android
    RABBIT_BUILD_THIRDLIBRARY: gdal osgearth
    QT_VERSION_DIR: 5.6
    QT_VERSION: 5.6.1
    TOOLCHAIN_VERSION: 4.8
    AUTOBUILD_ARCH: arm
    DOWNLOAD_FILE: https://sourceforge.net/projects/rabbitthirdlibrary/files/Release/rabbit_android4.8_arm_5.6.1_v$(appveyor_build_version).tar.gz/download
    RABBIT_USE_REPOSITORIES: "FALSE"
    PASSWORD:
      secure: 2WEtOQrdty3V3g0aEVvS3Q==

  - BUILD_TARGERT: windows_mingw
    RABBIT_BUILD_THIRDLIBRARY: gdal osgearth
    TOOLCHAIN_VERSION: 530
    QT_VERSION: qt5.7
    QT_ROOT: /C/Qt/5.7/mingw53_32
    AUTOBUILD_ARCH: x86
    DOWNLOAD_FILE: https://sourceforge.net/projects/rabbitthirdlibrary/files/Release/rabbit_windows_mingw530_x86_qt5.7_v$(appveyor_build_version).tar.gz/download
    RABBIT_USE_REPOSITORIES: "FALSE"
    PASSWORD:
      secure: 2WEtOQrdty3V3g0aEVvS3Q==

  - BUILD_TARGERT: windows_mingw
    RABBIT_BUILD_THIRDLIBRARY: gdal osgearth
    TOOLCHAIN_VERSION: 492
    QT_VERSION: qt5.6
    QT_ROOT: /C/Qt/5.6/mingw49_32
    AUTOBUILD_ARCH: x86
    DOWNLOAD_FILE: https://sourceforge.net/projects/rabbitthirdlibrary/files/Release/rabbit_windows_mingw492_x86_qt5.6_v$(appveyor_build_version).tar.gz/download
    RABBIT_USE_REPOSITORIES: "FALSE"
    PASSWORD:
      secure: 2WEtOQrdty3V3g0aEVvS3Q==
  ##### gdal osgearth #####
  
  ##### qxmpp qzxing #####
  - BUILD_TARGERT: windows_msvc
    TOOLCHAIN_VERSION: 14
    QT_VERSION: qt5.7
    RABBIT_BUILD_THIRDLIBRARY: qxmpp qzxing
    QT_ROOT: /C/Qt/5.7/msvc2015
    GENERATORS: "Visual Studio 14 2015"
    AUTOBUILD_ARCH: x86
    DOWNLOAD_FILE: https://sourceforge.net/projects/rabbitthirdlibrary/files/Release/rabbit_windows_msvc14_x86_qt5.7_v$(appveyor_build_version).tar.gz/download
    BUILD_END: "True"
    PASSWORD:
      secure: 2WEtOQrdty3V3g0aEVvS3Q==

  - BUILD_TARGERT: windows_msvc
    TOOLCHAIN_VERSION: 14
    QT_VERSION: qt5.6.1
    RABBIT_BUILD_THIRDLIBRARY: qxmpp qzxing
    QT_ROOT: /C/Qt/5.6/msvc2015
    GENERATORS: "Visual Studio 14 2015"
    AUTOBUILD_ARCH: x86
    DOWNLOAD_FILE: https://sourceforge.net/projects/rabbitthirdlibrary/files/Release/rabbit_windows_msvc14_x86_qt5.6.1_v$(appveyor_build_version).tar.gz/download
    RABBIT_USE_REPOSITORIES: "FALSE"
    BUILD_END: "True"
    PASSWORD:
      secure: 2WEtOQrdty3V3g0aEVvS3Q==

  - BUILD_TARGERT: windows_msvc
    TOOLCHAIN_VERSION: 12
    QT_VERSION: qt5.7
    RABBIT_BUILD_THIRDLIBRARY: qxmpp qzxing 
    QT_ROOT: /C/Qt/5.7/msvc2013
    GENERATORS: "Visual Studio 12 2013"
    AUTOBUILD_ARCH: x86
    DOWNLOAD_FILE: https://sourceforge.net/projects/rabbitthirdlibrary/files/Release/rabbit_windows_msvc12_x86_qt5.7_v$(appveyor_build_version).tar.gz/download
    BUILD_END: "True"
    PASSWORD:
      secure: 2WEtOQrdty3V3g0aEVvS3Q==

  - BUILD_TARGERT: windows_msvc
    TOOLCHAIN_VERSION: 12
    QT_VERSION: qt5.6.1
    RABBIT_BUILD_THIRDLIBRARY: qxmpp qzxing 
    QT_ROOT: /C/Qt/5.6/msvc2013
    GENERATORS: "Visual Studio 12 2013"
    AUTOBUILD_ARCH: x86
    DOWNLOAD_FILE: https://sourceforge.net/projects/rabbitthirdlibrary/files/Release/rabbit_windows_msvc12_x86_qt5.6.1_v$(appveyor_build_version).tar.gz/download
    RABBIT_USE_REPOSITORIES: "FALSE"
    BUILD_END: "True"
    PASSWORD:
      secure: 2WEtOQrdty3V3g0aEVvS3Q==

  - BUILD_TARGERT: android
    RABBIT_BUILD_THIRDLIBRARY: qxmpp qzxing 
    QT_VERSION_DIR: 5.7
    QT_VERSION: 5.7.0
    TOOLCHAIN_VERSION: 4.8
    AUTOBUILD_ARCH: arm
    DOWNLOAD_FILE: https://sourceforge.net/projects/rabbitthirdlibrary/files/Release/rabbit_android4.8_arm_5.7.0_v$(appveyor_build_version).tar.gz/download
    BUILD_END: "True"
    PASSWORD:
      secure: 2WEtOQrdty3V3g0aEVvS3Q==

  - BUILD_TARGERT: android
    RABBIT_BUILD_THIRDLIBRARY: qxmpp qzxing 
    QT_VERSION_DIR: 5.6
    QT_VERSION: 5.6.1
    TOOLCHAIN_VERSION: 4.8
    AUTOBUILD_ARCH: arm
    DOWNLOAD_FILE: https://sourceforge.net/projects/rabbitthirdlibrary/files/Release/rabbit_android4.8_arm_5.6.1_v$(appveyor_build_version).tar.gz/download
    RABBIT_USE_REPOSITORIES: "FALSE"
    BUILD_END: "True"
    PASSWORD:
      secure: 2WEtOQrdty3V3g0aEVvS3Q==

  - BUILD_TARGERT: windows_mingw
    TOOLCHAIN_VERSION: 530
    QT_VERSION: qt5.7
    RABBIT_BUILD_THIRDLIBRARY: qxmpp qzxing 
    QT_ROOT: /C/Qt/5.7/mingw53_32
    AUTOBUILD_ARCH: x86
    DOWNLOAD_FILE: https://sourceforge.net/projects/rabbitthirdlibrary/files/Release/rabbit_windows_mingw530_x86_qt5.7_v$(appveyor_build_version).tar.gz/download
    RABBIT_USE_REPOSITORIES: "FALSE"
    BUILD_END: "True"
    PASSWORD:
      secure: 2WEtOQrdty3V3g0aEVvS3Q==

  - BUILD_TARGERT: windows_mingw
    TOOLCHAIN_VERSION: 492
    QT_VERSION: qt5.6
    RABBIT_BUILD_THIRDLIBRARY: qxmpp qzxing 
    QT_ROOT: /C/Qt/5.6/mingw49_32
    AUTOBUILD_ARCH: x86
    DOWNLOAD_FILE: https://sourceforge.net/projects/rabbitthirdlibrary/files/Release/rabbit_windows_mingw492_x86_qt5.6_v$(appveyor_build_version).tar.gz/download
    RABBIT_USE_REPOSITORIES: "FALSE"
    BUILD_END: "True"
    PASSWORD:
      secure: 2WEtOQrdty3V3g0aEVvS3Q==
  ##### qxmpp qzxing #####

  ##### QT相关编译 #####

init:
  - set varch=%AUTOBUILD_ARCH%
  - set PROJECT_NAME=%APPVEYOR_PROJECT_NAME%
  - set BUILD_VERSION=%APPVEYOR_BUILD_VERSION%
  - if "%AUTOBUILD_ARCH%" == "x64" set varch=amd64
  - if "%BUILD_TARGERT%" == "windows_msvc" call "C:\Program Files (x86)\Microsoft Visual Studio %TOOLCHAIN_VERSION%.0\VC\vcvarsall.bat" %varch%
  - if "%BUILD_TARGERT%" == "windows_mingw" set MSYSTEM=MINGW32  #设置编译系统为MINGW32
  - echo NUMBER_OF_PROCESSORS=%NUMBER_OF_PROCESSORS%
  - echo PROCESSOR_IDENTIFIER=%PROCESSOR_IDENTIFIER%
  - echo QT_ROOT=%QT_ROOT%
  - echo QT_VERSION=%QT_VERSION%
  - del C:\msys64\usr\bin\link.exe

install:
  #- C:\msys64\usr\bin\pacman.exe -Syu --noconfirm 
  #- C:\msys64\autorebase.bat
  - C:\msys64\usr\bin\pacman.exe -S --noconfirm nasm yasm unzip expect #zip curl
  - C:\msys64\autorebase.bat
    
before_build:
  - cd %APPVEYOR_BUILD_FOLDER%
  - if "%BUILD_TARGERT%" == "android" C:\msys64\usr\bin\bash.exe %APPVEYOR_BUILD_FOLDER%\build_script\ci\build-install-tools-windows.sh

build_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - C:\msys64\usr\bin\bash.exe %APPVEYOR_BUILD_FOLDER%\build_script\ci\build.sh
  - C:\msys64\usr\bin\bash.exe %APPVEYOR_BUILD_FOLDER%\build_script\ci\Deploy.sh

after_build:
  - cd %APPVEYOR_BUILD_FOLDER%

artifacts:
#  - path rabbit_${BUILD_TARGERT}${TOOLCHAIN_VERSION}_${AUTOBUILD_ARCH}_${QT_VERSION}_v${BUILD_VERSION}.tar.gz
 # - path: ThirdLibrary/src
 #   name: RABBITThirdLibrarySource

  - path: $(BUILD_TARGERT)
    name: RABBIT_$(BUILD_TARGERT)$(TOOLCHAIN_VERSION)_$(AUTOBUILD_ARCH)_$(QT_VERSION)_v$(appveyor_build_version)
    type: zip

test: off

#deploy:
  #http://www.appveyor.com/docs/deployment/ftp
#  provider: FTP
  #https://sourceforge.net/p/forge/documentation/SFTP/
#  protocol: sftp
#  host: frs.sourceforge.net
#  username: kl222,rabbitthirdlibrary
  #密码用这个加密 https://ci.appveyor.com/tools/encrypt
#  PASSWORD:
#    secure: 2WEtOQrdty3V3g0aEVvS3Q==
  #link pfs to  /home/frs/project/r/ra/rabbitthirdlibrary
#  folder: pfs/Release
#  active_mode: false

#deploy:
#  provider: GitHub
#  release: RABBIT-third-library-v$(appveyor_build_version)
#  description: 'RABBIT-third-library-v$(appveyor_build_version)'
#  #token 在这个地址产生 https://github.com/settings/tokens 用这个加密 https://ci.appveyor.com/tools/encrypt
#  auth_token:
#    secure: ZwS9M6Ide+GfM4kLxJ5b9tRoB1wn/56nZRCAIP6Z7s3+YwcE+cx0Dv0d6X82lidF
#  draft: false
#  prerelease: false
#  on:
#    branch: master                 # release from master branch only
#    #appveyor_repo_tag: true        # deploy on tag push only
