#TODO:版本变更时，修改成相应的版本
version: '0.1.1.{build}'

image: Visual Studio 2015

environment:
  matrix:
  ##### msvc 2017 ########
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    BUILD_TARGERT: windows_msvc
    RABBIT_TOOLCHAIN_VERSION: 15
    RABBIT_ARCH: x64
    RABBIT_CONFIG: Release
    QT_VERSION: NO
    QT_ROOT: NO

  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    BUILD_TARGERT: windows_msvc
    RABBIT_TOOLCHAIN_VERSION: 15
    RABBIT_ARCH: x64
    RABBIT_CONFIG: Debug
    QT_VERSION: NO
    QT_ROOT: NO
    
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    BUILD_TARGERT: windows_msvc
    RABBIT_TOOLCHAIN_VERSION: 15
    RABBIT_ARCH: x86
    RABBIT_CONFIG: Release
    QT_VERSION: NO
    QT_ROOT: NO
    
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    BUILD_TARGERT: windows_msvc
    RABBIT_TOOLCHAIN_VERSION: 15
    RABBIT_ARCH: x86
    RABBIT_CONFIG: Debug
    QT_VERSION: NO
    QT_ROOT: NO
    
  ##### msvc 2015 ########
  - BUILD_TARGERT: windows_msvc
    RABBIT_TOOLCHAIN_VERSION: 14
    RABBIT_ARCH: x64
    RABBIT_CONFIG: Release
    QT_VERSION: NO
    QT_ROOT: NO
    
  - BUILD_TARGERT: windows_msvc
    RABBIT_TOOLCHAIN_VERSION: 14
    RABBIT_ARCH: x64
    RABBIT_CONFIG: Debug
    QT_VERSION: NO
    QT_ROOT: NO
  
  - BUILD_TARGERT: windows_msvc
    RABBIT_TOOLCHAIN_VERSION: 14
    RABBIT_ARCH: x86
    RABBIT_CONFIG: Release
    QT_VERSION: NO
    QT_ROOT: NO
  
  - BUILD_TARGERT: windows_msvc
    RABBIT_TOOLCHAIN_VERSION: 14
    RABBIT_ARCH: x86
    RABBIT_CONFIG: Debug
    QT_VERSION: NO
    QT_ROOT: NO
    
  ##### msvc 2013 ########
  - BUILD_TARGERT: windows_msvc
    RABBIT_TOOLCHAIN_VERSION: 12
    RABBIT_ARCH: x64
    RABBIT_CONFIG: Release
    QT_VERSION: NO
    QT_ROOT: NO

  - BUILD_TARGERT: windows_msvc
    RABBIT_TOOLCHAIN_VERSION: 12
    RABBIT_ARCH: x86
    RABBIT_CONFIG: Release
    QT_VERSION: NO
    QT_ROOT: NO
  
  ##### mingw ########
  - BUILD_TARGERT: windows_mingw
    RABBIT_TOOLCHAIN_VERSION: 530
    RABBIT_ARCH: x86
    RABBIT_CONFIG: Release
    QT_VERSION: NO
    QT_ROOT: NO
    
  - BUILD_TARGERT: windows_mingw
    RABBIT_TOOLCHAIN_VERSION: 530
    RABBIT_ARCH: x86
    RABBIT_CONFIG: Debug
    QT_VERSION: NO
    QT_ROOT: NO

  - BUILD_TARGERT: windows_mingw
    RABBIT_TOOLCHAIN_VERSION: 492
    RABBIT_ARCH: x86
    RABBIT_CONFIG: Release
    QT_VERSION: NO
    QT_ROOT: NO

  - BUILD_TARGERT: windows_mingw
    RABBIT_TOOLCHAIN_VERSION: 482
    RABBIT_ARCH: x86
    RABBIT_CONFIG: Release
    QT_VERSION: NO
    QT_ROOT: NO
    
init:
  - set varch=%RABBIT_ARCH%
  - set PROJECT_NAME=%APPVEYOR_PROJECT_NAME%
  - set BUILD_VERSION=%APPVEYOR_BUILD_VERSION%
  #- set RABBIT_USE_REPOSITORIES="FALSE"
  - if "%RABBIT_ARCH%" == "x64" set varch=amd64
  - if "%BUILD_TARGERT%" == "windows_msvc" if %RABBIT_TOOLCHAIN_VERSION% LSS 15 (call "C:\Program Files (x86)\Microsoft Visual Studio %RABBIT_TOOLCHAIN_VERSION%.0\VC\vcvarsall.bat" %varch%) else (call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" %varch%)
  - if "%BUILD_TARGERT%" == "windows_mingw" set MSYSTEM=MINGW32  #设置编译系统为MINGW32
  - del C:\msys64\usr\bin\link.exe

install:
  - if not "%BUILD_TARGERT%" == "android" C:\msys64\usr\bin\pacman.exe -S --noconfirm nasm yasm 
  - C:\msys64\usr\bin\pacman.exe -S --noconfirm unzip expect #zip curl
  - C:\msys64\autorebase.bat
    
before_build:
  - cd %APPVEYOR_BUILD_FOLDER%
  - if "%BUILD_TARGERT%" == "android" C:\msys64\usr\bin\bash.exe %APPVEYOR_BUILD_FOLDER%\build_script\ci\build-install-tools-windows.sh
  
build_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - C:\msys64\usr\bin\bash.exe %APPVEYOR_BUILD_FOLDER%\build_script\ci\build.sh
  #- C:\msys64\usr\bin\bash.exe %APPVEYOR_BUILD_FOLDER%\build_script\ci\Deploy.sh

after_build:
  - cd %APPVEYOR_BUILD_FOLDER%

artifacts:
  - path: $(BUILD_TARGERT)$(RABBIT_TOOLCHAIN_VERSION)_$(RABBIT_ARCH)_qt$(QT_VERSION)_$(RABBIT_CONFIG)
    name: RABBIT_$(BUILD_TARGERT)$(RABBIT_TOOLCHAIN_VERSION)_$(RABBIT_ARCH)_qt$(QT_VERSION)_$(QT_VERSION)_$(RABBIT_CONFIG)_v$(appveyor_build_version)
    type: zip

test: off

#deploy:
  #http://www.appveyor.com/docs/deployment/ftp
#  provider: FTP
  #https://sourceforge.net/p/forge/documentation/SFTP/
#  protocol: sftp
#  host: frs.sourceforge.net
#  username: kl222,rabbitthirdlibrary
  #密码用这个加密 https://ci.appveyor.com/tools/encrypt
#  PASSWORD:
#    secure: 2WEtOQrdty3V3g0aEVvS3Q==
  #link pfs to  /home/frs/project/r/ra/rabbitthirdlibrary
#  folder: pfs/Release
#  active_mode: false

#deploy:
#  provider: GitHub
#  release: RABBIT-third-library-v$(appveyor_build_version)
#  description: 'RABBIT-third-library-v$(appveyor_build_version)'
#  #token 在这个地址产生 https://github.com/settings/tokens 用这个加密 https://ci.appveyor.com/tools/encrypt
#  auth_token:
#    secure: ZwS9M6Ide+GfM4kLxJ5b9tRoB1wn/56nZRCAIP6Z7s3+YwcE+cx0Dv0d6X82lidF
#  draft: false
#  prerelease: false
#  on:
#    branch: master                 # release from master branch only
#    #appveyor_repo_tag: true        # deploy on tag push only
