version: 'v0.2.9-27-g8e4e86d.{build}'

cache:
  - Package

environment:
  BUILD_VERSION: v0.2.9-27-g8e4e86d-27-g8e4e86d
  TimeOutMins: 2
  #ApiKey:
  #  secure: qex0da587ygmywf4315g

  #QT_USER:
  #  secure: EoBPaPuJ6u9UDYpQWjKhUg==
  #QT_PASSWORD:
  #  secure: ejAYGgB+3sBispRxUSr0xw==

  matrix:
  ##### msvc 2017 debug ########
  - RABBIT_NUMBER: 0
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    BUILD_TARGERT: windows_msvc
    TOOLCHAIN_VERSION: 15
    BUILD_ARCH: x86
    RABBIT_CONFIG: Debug

  - RABBIT_NUMBER: 1
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    BUILD_TARGERT: windows_msvc
    TOOLCHAIN_VERSION: 15
    BUILD_ARCH: x86
    RABBIT_CONFIG: Debug

  - RABBIT_NUMBER: 2
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    BUILD_TARGERT: windows_msvc
    TOOLCHAIN_VERSION: 15
    BUILD_ARCH: x86
    RABBIT_CONFIG: Debug
    QT_ROOT: C:\Qt\5.13\msvc2017

  - RABBIT_NUMBER: 2
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    BUILD_TARGERT: windows_msvc
    TOOLCHAIN_VERSION: 15
    BUILD_ARCH: x86
    RABBIT_CONFIG: Debug
    QT_ROOT: C:\Qt\5.12\msvc2017
    
  ##### msvc 2017 ########
  - RABBIT_NUMBER: 0
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    BUILD_TARGERT: windows_msvc
    TOOLCHAIN_VERSION: 15
    BUILD_ARCH: x86
    RABBIT_CONFIG: Release

  - RABBIT_NUMBER: 1
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    BUILD_TARGERT: windows_msvc
    TOOLCHAIN_VERSION: 15
    BUILD_ARCH: x86
    RABBIT_CONFIG: Release

  - RABBIT_NUMBER: 2
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    BUILD_TARGERT: windows_msvc
    TOOLCHAIN_VERSION: 15
    BUILD_ARCH: x86
    RABBIT_CONFIG: Release
    QT_ROOT: C:\Qt\5.12\msvc2017

  - RABBIT_NUMBER: 0
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    BUILD_TARGERT: windows_msvc
    TOOLCHAIN_VERSION: 15
    BUILD_ARCH: x64
    RABBIT_CONFIG: Release
    
  - RABBIT_NUMBER: 1
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    BUILD_TARGERT: windows_msvc
    TOOLCHAIN_VERSION: 15
    BUILD_ARCH: x64
    RABBIT_CONFIG: Release

  - RABBIT_NUMBER: 2
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    BUILD_TARGERT: windows_msvc
    TOOLCHAIN_VERSION: 15
    BUILD_ARCH: x64
    RABBIT_CONFIG: Release
    QT_ROOT: C:\Qt\5.13\msvc2017_64
    
  ##### msvc 2015 ########
  - RABBIT_NUMBER: 0
    BUILD_TARGERT: windows_msvc
    TOOLCHAIN_VERSION: 14
    BUILD_ARCH: x86
    RABBIT_CONFIG: Release

  - RABBIT_NUMBER: 1
    BUILD_TARGERT: windows_msvc
    TOOLCHAIN_VERSION: 14
    BUILD_ARCH: x86
    RABBIT_CONFIG: Release
    
  - RABBIT_NUMBER: 2
    BUILD_TARGERT: windows_msvc
    TOOLCHAIN_VERSION: 14
    BUILD_ARCH: x86
    RABBIT_CONFIG: Release
    QT_ROOT: C:\Qt\5.9\msvc2015

  - RABBIT_NUMBER: 0
    BUILD_TARGERT: windows_msvc
    TOOLCHAIN_VERSION: 14
    BUILD_ARCH: x64
    RABBIT_CONFIG: Release
  
  - RABBIT_NUMBER: 1
    BUILD_TARGERT: windows_msvc
    TOOLCHAIN_VERSION: 14
    BUILD_ARCH: x64
    RABBIT_CONFIG: Release

  - RABBIT_NUMBER: 2
    BUILD_TARGERT: windows_msvc
    TOOLCHAIN_VERSION: 14
    BUILD_ARCH: x64
    RABBIT_CONFIG: Release
    QT_ROOT: C:\Qt\5.10\msvc2015_64
    
  ##### mingw ########
  - RABBIT_NUMBER: 0
    BUILD_TARGERT: windows_mingw
    TOOLCHAIN_VERSION: 530_32
    BUILD_ARCH: x86
    RABBIT_CONFIG: Release
    
  - RABBIT_NUMBER: 1
    BUILD_TARGERT: windows_mingw
    TOOLCHAIN_VERSION: 530_32
    BUILD_ARCH: x86
    RABBIT_CONFIG: Release

  - RABBIT_NUMBER: 2
    BUILD_TARGERT: windows_mingw
    TOOLCHAIN_VERSION: 530_32
    BUILD_ARCH: x86
    RABBIT_CONFIG: Release
    QT_ROOT: C:\Qt\5.9\mingw53_32
    
  #- RABBIT_NUMBER: 0
  #  BUILD_TARGERT: windows_mingw
  #  TOOLCHAIN_VERSION: 730_64
  #  BUILD_ARCH: x64
  #  RABBIT_CONFIG: Release

  #- RABBIT_NUMBER: 0
  #  BUILD_TARGERT: windows_mingw
  #  TOOLCHAIN_VERSION: 730_64
  #  BUILD_ARCH: x64
  #  RABBIT_CONFIG: Release

#QT_ROOT: C:\Qt\5.12\mingw73_64

  ##### android ########
  - RABBIT_NUMBER: 0
    BUILD_TARGERT: android
    TOOLCHAIN_VERSION: 4.9
    BUILD_ARCH: arm
    RABBIT_CONFIG: Release
    ANDROID_API: android-24
    ANDROID_ARM_NEON: ON

  - RABBIT_NUMBER: 1
    BUILD_TARGERT: android
    TOOLCHAIN_VERSION: 4.9
    BUILD_ARCH: arm
    RABBIT_CONFIG: Release
    ANDROID_API: android-24
    ANDROID_ARM_NEON: ON

  - RABBIT_NUMBER: 2
    BUILD_TARGERT: android
    TOOLCHAIN_VERSION: 4.9
    BUILD_ARCH: arm
    RABBIT_CONFIG: Release
    ANDROID_API: android-24
    ANDROID_ARM_NEON: ON
    QT_VERSION_DIR: 5.12
    QT_VERSION: 5.12.6
    DOWNLOAD_QT: TRUE

  - RABBIT_NUMBER: 0
    BUILD_TARGERT: android
    TOOLCHAIN_VERSION: 4.9
    BUILD_ARCH: arm64
    RABBIT_CONFIG: Release
    ANDROID_API: android-24
    ANDROID_ARM_NEON: ON

  - RABBIT_NUMBER: 1
    BUILD_TARGERT: android
    TOOLCHAIN_VERSION: 4.9
    BUILD_ARCH: arm64
    RABBIT_CONFIG: Release
    ANDROID_API: android-24
    ANDROID_ARM_NEON: ON

  - RABBIT_NUMBER: 2
    BUILD_TARGERT: android
    TOOLCHAIN_VERSION: 4.9
    BUILD_ARCH: arm64
    RABBIT_CONFIG: Release
    ANDROID_API: android-24
    ANDROID_ARM_NEON: ON
    QT_VERSION_DIR: 5.12
    QT_VERSION: 5.12.6
    DOWNLOAD_QT: TRUE
    
  - RABBIT_NUMBER: 0
    BUILD_TARGERT: android
    TOOLCHAIN_VERSION: 4.9
    BUILD_ARCH: x86
    RABBIT_CONFIG: Release
    ANDROID_API: android-24

  - RABBIT_NUMBER: 1
    BUILD_TARGERT: android
    TOOLCHAIN_VERSION: 4.9
    BUILD_ARCH: x86
    RABBIT_CONFIG: Release
    ANDROID_API: android-24

  - RABBIT_NUMBER: 2
    BUILD_TARGERT: android
    TOOLCHAIN_VERSION: 4.9
    BUILD_ARCH: x86
    RABBIT_CONFIG: Release
    ANDROID_API: android-24
    QT_VERSION_DIR: 5.12
    QT_VERSION: 5.12.6
    DOWNLOAD_QT: TRUE

  - RABBIT_NUMBER: 0
    BUILD_TARGERT: android
    TOOLCHAIN_VERSION: 4.9
    BUILD_ARCH: x86_64
    RABBIT_CONFIG: Release
    ANDROID_API: android-24

  - RABBIT_NUMBER: 1
    BUILD_TARGERT: android
    TOOLCHAIN_VERSION: 4.9
    BUILD_ARCH: x86_64
    RABBIT_CONFIG: Release
    ANDROID_API: android-24

  - RABBIT_NUMBER: 2
    BUILD_TARGERT: android
    TOOLCHAIN_VERSION: 4.9
    BUILD_ARCH: x86_64
    RABBIT_CONFIG: Release
    ANDROID_API: android-24
    QT_VERSION_DIR: 5.12
    QT_VERSION: 5.12.6
    DOWNLOAD_QT: TRUE 

matrix:
  fast_finish: false

init:
  - set varch=%BUILD_ARCH%
  - if "%BUILD_ARCH%" == "x64" set varch=amd64
  - if "%BUILD_TARGERT%" == "windows_msvc" if %TOOLCHAIN_VERSION% LSS 15 (call "C:\Program Files (x86)\Microsoft Visual Studio %TOOLCHAIN_VERSION%.0\VC\vcvarsall.bat" %varch%) else (call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" %varch%)  
  - echo NUMBER_OF_PROCESSORS=%NUMBER_OF_PROCESSORS%
  - echo PROCESSOR_IDENTIFIER=%PROCESSOR_IDENTIFIER%
  - if NOT "%QT_ROOT%" == "" for /f "delims=" %%i in ('%QT_ROOT%/bin/qmake -query QT_VERSION') do (set QT_VERSION=%%i) 
  - echo QT_ROOT=%QT_ROOT%
  - echo QT_VERSION=%QT_VERSION%
  - echo BUILD_VERSION=%BUILD_VERSION%
  - del C:\msys64\usr\bin\link.exe

install:
  - C:\msys64\autorebase.bat
  - C:\msys64\usr\bin\pacman.exe -S --noconfirm unzip nasm yasm
  #- if "%BUILD_TARGERT%"=="windows_mingw" set PATH=C:\Qt\Tools\mingw%TOOLCHAIN_VERSION%_32\bin;%PATH%
  - if "%BUILD_TARGERT%" == "windows_mingw" set MSYSTEM=MINGW32  #设置编译系统为MINGW32
  - del C:\msys64\usr\bin\link.exe
  - cd %APPVEYOR_BUILD_FOLDER%
  #- ps: build_script\ci\download_library_android.ps1
  - ps: build_script\ci\download_library.ps1

before_build:
  - cd %APPVEYOR_BUILD_FOLDER%
  - if "%BUILD_TARGERT%" == "android" C:\msys64\usr\bin\bash.exe %APPVEYOR_BUILD_FOLDER%\build_script\ci\build-install-tools-windows.sh

build_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - C:\msys64\usr\bin\bash.exe %APPVEYOR_BUILD_FOLDER%\build_script\ci\build_windows.sh

artifacts:
  - path: build_$(BUILD_TARGERT)
  - path: $(BUILD_TARGERT)$(TOOLCHAIN_VERSION)_$(BUILD_ARCH)_$(RABBIT_CONFIG)_$(BUILD_VERSION)
  - path: $(BUILD_TARGERT)$(TOOLCHAIN_VERSION)_$(BUILD_ARCH)_$(RABBIT_CONFIG)_$(BUILD_VERSION)_in_windows
  - path: $(BUILD_TARGERT)$(TOOLCHAIN_VERSION)_$(BUILD_ARCH)_$(RABBIT_CONFIG)_qt$(QT_VERSION)_$(BUILD_VERSION)
  - path: $(BUILD_TARGERT)$(TOOLCHAIN_VERSION)_$(BUILD_ARCH)_$(RABBIT_CONFIG)_qt$(QT_VERSION)_$(BUILD_VERSION)_in_windows
  
test: off

#See:https://www.appveyor.com/docs/deployment/github/
deploy:
  - provider: GitHub
    #release: RabbitThirdLibrary_$(BUILD_VERSION)
    #description: 'Release Tasks $(APPVEYOR_REPO_TAG_NAME) on windows'
    #token : https://github.com/settings/tokens
    #password encrypt: https://ci.appveyor.com/tools/encrypt
    auth_token:
      secure: NPGYJzqYbViyGy0og49nCXxnj98vKqjxsgAd45rMhB9L1Vp1hCYp+Ku4C9qhe+vC
    #artifact: RabbitThirdLibrary_$(BUILD_TARGERT)$(TOOLCHAIN_VERSION)_$(BUILD_ARCH)_$(QT_VERSION)_$(BUILD_VERSION)
    #draft: true
    #prerelease: true
    on:
      appveyor_repo_tag: true        # deploy on tag push only
      RABBIT_NUMBER: 2
