name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: windows-latest
            triplet: x86-window
          - os: windows-latest
            triplet: x64-window
          - os: ubuntu-latest
            triplet: x64-linux
          - os: macos-latest
            triplet: x64-osx

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
      
    - name: run-vcpkg
      # You may pin to the exact commit or the version.
      # uses: lukka/run-vcpkg@a1b6a0046a28c09f4bcc8caa9eecec9a8e512152
      uses: lukka/run-vcpkg@v6.1
      with:
        # Indicates whether to only setup vcpkg (i.e. installing it and setting the environment variables VCPKG_ROOT, RUNVCPK_VCPKG_ROOT), without installing any port.
        #setupOnly: # optional
        vcpkgGitURL: https://github.com/KangLin/vcpkg.git
        vcpkgGitCommitId: 37b05428f33d148ad849f5c4e4e84ac33d60299a
        vcpkgDirectory: ${{ runner.workspace }}/vcpkg/
        vcpkgTriplet: '${{ matrix.triplet }}'
        vcpkgArguments: 'openssl libssh freerdp'
  
